# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exportacion', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'dato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodoanual',
            fields=[
                ('anio', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'periodoanual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodomensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'periodomensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodotrimestral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'periodotrimestral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productointernobruto',
            fields=[
                ('periodotrimestral', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='importaciones.Periodotrimestral')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'productointernobruto',
                'managed': False,
            },
        ),
    ]
